### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DagmaraSz** [groundberry/flashcards-client#27]
Hey, 
Started using your flashcards. Would be great if they had basic text formatting. I specifically bumped into the issue of not being able to put some text in a new line in my answer. Not sure if you're going to be doing any more on this project, but if you are, thought I might as well formally create an issue ;)

**Comment by groundberry** [comment]
Thank you for your feedback Dagmara :)
Flashcards uses Markdown, so you can add text in a new line by clicking return twice. You also can add lists just by adding an * before each line, and so on.

**Comment by DagmaraSz** [comment]
Awesome! Sorry I missed that :)
